#!/usr/bin/env python3
"""
RACS Codegen — Expression Tree → ARM Cortex-M4 C code
======================================================
1. tree → C function `float ctrl(float e, float ie, float de, float r, float y)`
2. compile with clang (--target=armv7em-none-eabi -mcpu=cortex-m4)
3. link with ld.lld (bare-metal MPS2-AN386)
4. run on QEMU, measure REAL cycles via DWT->CYCCNT
5. compare with the Python cycle model (racy cycles())
"""
import os, subprocess, tempfile, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

CODEGEN_DIR = os.path.dirname(os.path.abspath(__file__))

# ──────────────────────────────────────────────
#  Tree → C
# ──────────────────────────────────────────────

def tree_to_c(tree, func_name="ctrl"):
    """Generate C code from expression tree.
    Args order: e, ie, de, r, y (matches racs2 VARS).
    sin/cos/sqrt → own soft implementations (no libm on bare metal)."""
    lines = []
    lines.append("/* Auto-generated by RACS codegen */")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("/* Soft float lib for bare metal (no libm) */")
    lines.append("static float soft_sinf(float x) {")
    lines.append("    /* range reduce to [-pi, pi] */")
    lines.append("    while (x > 3.14159265f) x -= 6.28318531f;")
    lines.append("    while (x < -3.14159265f) x += 6.28318531f;")
    lines.append("    float x2 = x * x;")
    lines.append("    /* Taylor: sin(x)=x - x^3/6 + x^5/120 - x^7/5040 */")
    lines.append("    return x * (1.0f - x2/6.0f + x2*x2/120.0f - x2*x2*x2/5040.0f);")
    lines.append("}")
    lines.append("static float soft_cosf(float x) {")
    lines.append("    while (x > 3.14159265f) x -= 6.28318531f;")
    lines.append("    while (x < -3.14159265f) x += 6.28318531f;")
    lines.append("    float x2 = x * x;")
    lines.append("    /* cos(x)=1 - x^2/2 + x^4/24 - x^6/720 */")
    lines.append("    return 1.0f - x2/2.0f + x2*x2/24.0f - x2*x2*x2/720.0f;")
    lines.append("}")
    lines.append("static float soft_sqrtf(float x) {")
    lines.append("    if (x <= 0.0f) return 0.0f;")
    lines.append("    float y = x; float g = x * 0.5f;")
    lines.append("    for (int i = 0; i < 8; i++) g = 0.5f * (g + y / g);")
    lines.append("    return g;")
    lines.append("}")
    lines.append("")
    lines.append(f"float {func_name}(float e, float ie, float de, float r, float y)")
    lines.append("{")
    lines.append(f"    return {_expr(tree)};")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _expr(n):
    if n.op == 'const':
        return f"{n.val:.8f}f"
    if n.op == 'var':
        return n.val
    if n.op == 'neg':
        return f"(-({_expr(n.left)}))"
    if n.op == 'abs':
        return f"__builtin_fabsf({_expr(n.left)})"
    if n.op == 'sin':
        return f"soft_sinf({_expr(n.left)})"
    if n.op == 'cos':
        return f"soft_cosf({_expr(n.left)})"
    if n.op == 'sqrt':
        return f"soft_sqrtf({_expr(n.left)})"
    if n.op == 'add':
        return f"(({_expr(n.left)}) + ({_expr(n.right)}))"
    if n.op == 'sub':
        return f"(({_expr(n.left)}) - ({_expr(n.right)}))"
    if n.op == 'mul':
        return f"(({_expr(n.left)}) * ({_expr(n.right)}))"
    if n.op == 'div':
        return f"(({_expr(n.left)}) / ({_expr(n.right)}))"
    if n.op == 'min':
        return f"(({_expr(n.left)}) < ({_expr(n.right)}) ? ({_expr(n.left)}) : ({_expr(n.right)}))"
    if n.op == 'max':
        return f"(({_expr(n.left)}) > ({_expr(n.right)}) ? ({_expr(n.left)}) : ({_expr(n.right)}))"
    return "0.0f"


# ──────────────────────────────────────────────
#  Compile / link / run
# ──────────────────────────────────────────────

def compile_c(c_source: str, out_dir, verbose=False):
    """Compile C source → bare-metal ELF for MPS2-AN386."""
    os.makedirs(out_dir, exist_ok=True)
    c_path = os.path.join(out_dir, "ctrl.c")
    with open(c_path, "w") as f:
        f.write(c_source)

    obj = os.path.join(out_dir, "ctrl.o")
    elf = os.path.join(out_dir, "firmware.elf")
    binp = os.path.join(out_dir, "firmware.bin")

    # main that measures cycles
    main_c = _make_main()
    main_path = os.path.join(out_dir, "main.c")
    with open(main_path, "w") as f:
        f.write(main_c)

    support = os.path.join(CODEGEN_DIR, "support.c")
    startup = os.path.join(CODEGEN_DIR, "startup.s")
    linker = os.path.join(CODEGEN_DIR, "mps2_an386.ld")

    cc = ["clang", "--target=armv7em-none-eabi",
          "-mcpu=cortex-m4", "-mfloat-abi=softfp", "-mfpu=fpv4-sp-d16",
          "-O2", "-ffreestanding", "-fno-builtin", "-c"]

    # compile ctrl.c
    r = subprocess.run(cc + [c_path, "-o", os.path.join(out_dir, "ctrl_ctrl.o")],
                       capture_output=True, text=True)
    if r.returncode != 0:
        return None, f"compile ctrl failed: {r.stderr}"

    # compile main.c
    r = subprocess.run(cc + [main_path, "-o", os.path.join(out_dir, "ctrl_main.o")],
                       capture_output=True, text=True)
    if r.returncode != 0:
        return None, f"compile main failed: {r.stderr}"

    # compile support.c
    r = subprocess.run(cc + [support, "-o", os.path.join(out_dir, "ctrl_support.o")],
                       capture_output=True, text=True)
    if r.returncode != 0:
        return None, f"compile support failed: {r.stderr}"

    # compile startup.s
    r = subprocess.run(["clang", "--target=armv7em-none-eabi", "-mcpu=cortex-m4",
                        "-c", startup, "-o", os.path.join(out_dir, "startup.o")],
                       capture_output=True, text=True)
    if r.returncode != 0:
        return None, f"compile startup failed: {r.stderr}"

    # link
    r = subprocess.run(
        ["ld.lld", "-T", linker,
         os.path.join(out_dir, "startup.o"),
         os.path.join(out_dir, "ctrl_ctrl.o"),
         os.path.join(out_dir, "ctrl_main.o"),
         os.path.join(out_dir, "ctrl_support.o"),
         "-o", elf],
        capture_output=True, text=True)
    if r.returncode != 0:
        return None, f"link failed: {r.stderr}"

    # to bin
    r = subprocess.run(["llvm-objcopy", "-O", "binary", elf, binp],
                       capture_output=True, text=True)
    if r.returncode != 0:
        return None, f"objcopy failed: {r.stderr}"

    return elf, None


def _make_main():
    """Main: init DWT, call ctrl() 1000x, print avg cycles.
    Uses naked benchmark function to avoid FPU d8-d15 pushes
    (QEMU STM32L475 faults on vpush d8+ with lazy stacking)."""
    return """
#include <stdint.h>

extern float ctrl(float e, float ie, float de, float r, float y);
void dbg_init(void);
uint32_t dbg_cycles(void);
void dbg_print_str(const char*);
void dbg_print_u32(uint32_t);

static void exit_qemu(void) {
    register uint32_t r0 asm("r0") = 0x18;   /* SYS_EXIT */
    register uint32_t r1 asm("r1") = 0x20026; /* ADP_Stopped_ApplicationExit */
    asm volatile("bkpt 0xAB" : : "r"(r0), "r"(r1) : "memory");
}

/* naked: no prologue/epilogue, no FPU register saves.
   softfp ABI: e,r0 | ie,r1 | de,r2 | r,r3 | y,[sp] — float return in r0. */
__attribute__((naked, noinline)) uint32_t bench_ctrl(uint32_t iters) {
    asm volatile(
        "push {r4, r5, r6, lr}\\n"
        "sub sp, sp, #8\\n"
        "ldr r6, =0x3f000000\\n"    /* y = 0.5f */
        "str r6, [sp]\\n"
        "mov r5, r0\\n"             /* iters */
        "1:\\n"
        "ldr r0, =0x3f000000\\n"    /* e = 0.5f */
        "ldr r1, =0x3dcccccd\\n"    /* ie = 0.1f */
        "ldr r2, =0xbc23d70a\\n"    /* de = -0.02f */
        "ldr r3, =0x3f800000\\n"    /* r = 1.0f */
        "ldr r4, =0x3f000000\\n"    /* y = 0.5f */
        "str r4, [sp]\\n"
        "bl ctrl\\n"
        "subs r5, #1\\n"
        "bne 1b\\n"
        "mov r0, r5\\n"
        "add sp, sp, #8\\n"
        "pop {r4, r5, r6, pc}\\n"
    );
}

int main(void) {
    dbg_init();

    /* CALIBRATION: 100 nops → determine SysTick scale */
    uint32_t c0 = dbg_cycles();
    asm volatile(".rept 100\\nnop\\n.endr");
    uint32_t c1 = dbg_cycles();
    dbg_print_str("calib_100nop_ticks=");
    dbg_print_u32(c1 - c0);
    dbg_print_str("\\n");

    uint32_t t0 = dbg_cycles();
    uint32_t sink = bench_ctrl(1000);
    uint32_t t1 = dbg_cycles();
    uint32_t total = t1 - t0;
    uint32_t avg = total / 1000;

    dbg_print_str("cycles_avg=");
    dbg_print_u32(avg);
    dbg_print_str("cycles_total=");
    dbg_print_u32(total);
    dbg_print_str("sink=");
    dbg_print_u32(sink);
    dbg_print_str("\\n");

    exit_qemu();
    return 0;
}
"""


def run_qemu(elf_path, timeout=10):
    """Run firmware on QEMU MPS2-AN386 with semihosting."""
    try:
        r = subprocess.run(
            ["qemu-system-arm", "-machine", "mps2-an386",
             "-cpu", "cortex-m4", "-nographic",
             "-semihosting-config", "enable=on,target=native",
             "-kernel", elf_path, "-d", "guest_errors", "-no-reboot"],
            capture_output=True, text=True, timeout=timeout)
        return r.stdout + r.stderr
    except subprocess.TimeoutExpired as e:
        # collect partial output
        out = (e.stdout or b"") + (e.stderr or b"")
        if isinstance(out, bytes):
            out = out.decode(errors="replace")
        return out + "\n[TIMEOUT]"


def measure_real_cycles(tree, out_dir=None, verbose=False):
    """Full pipeline: tree → C → ELF → disassemble → static cycle count (WCET).
    Also runs on QEMU for smoke validation.
    Returns (static_cycles, qemu_avg, info_dict)."""
    c_src = tree_to_c(tree)
    out_dir = out_dir or tempfile.mkdtemp(prefix="racs_cg_")
    elf, err = compile_c(c_src, out_dir, verbose=verbose)
    if elf is None:
        return None, None, {"error": err}

    # disassemble and extract ctrl() body
    dis = subprocess.run(["llvm-objdump", "-d", elf],
                         capture_output=True, text=True).stdout
    ctrl_asm = _extract_func_asm(dis, "ctrl")

    # static WCET cycle count from Cortex-M4 latency table
    static_cycles = count_cycles_asm(ctrl_asm)
    info = {
        "asm": ctrl_asm,
        "asm_instr_count": len(ctrl_asm),
        "elf_path": elf,
    }

    # QEMU smoke run
    qemu_out = run_qemu(elf)
    avg = None
    for line in qemu_out.splitlines():
        if "cycles_avg=" in line:
            try:
                avg = int(line.split("=")[1].strip(), 16)
            except ValueError:
                pass
    info["qemu_output"] = qemu_out[-300:]
    info["qemu_avg"] = avg
    return static_cycles, avg, info


def _extract_func_asm(disasm_text, func_name):
    """Extract instruction lines for a function from objdump output.
    Stops at first bx lr / pop pc (function end)."""
    import re
    lines = []
    in_func = False
    for line in disasm_text.splitlines():
        if ">:" in line and func_name in line:
            in_func = True
            continue
        if in_func and ">:" in line:
            break
        if in_func and ":" in line:
            # find mnemonic: first alphabetic token after address+bytes
            m = re.search(r':\s+(?:[0-9a-f]{2,8}\s+)*([a-z][a-z0-9.]+)', line)
            if m:
                mn = m.group(1)
                lines.append(mn)
                if mn.startswith(("bx", "pop")):
                    break
    return lines


# Cortex-M4 instruction latency table (cycles, worst-case for FPU ops)
# Based on ARM Cortex-M4 TRM (FPU: 1-cycle for VADD/VSUB/VMUL, 14 for VDIV,
# 1-2 for VLDR/VSTR, branch 1-3 for BL/BX, etc.)
CM4_LATENCY = {
    'vadd': 1, 'vsub': 1, 'vmul': 1, 'vdiv': 14,
    'vmla': 1, 'vmls': 1, 'vnmul': 1, 'vnmla': 1, 'vnmls': 1,
    'vabs': 1, 'vneg': 1, 'vsqrt': 14, 'vcmp': 1,
    'vcvt': 1, 'vmov': 1, 'vldr': 2, 'vstr': 2,
    'vpush': 2, 'vpop': 2,
    'add': 1, 'sub': 1, 'mul': 1, 'mov': 1, 'movs': 1,
    'ldr': 2, 'str': 2, 'push': 1, 'pop': 1, 'bx': 3,
    'bl': 3, 'b': 3, 'bne': 3, 'beq': 3, 'bge': 3, 'cmp': 1,
    'nop': 1, 'orr': 1, 'and': 1, 'bic': 1, 'eor': 1, 'lsl': 1,
    'lsr': 1, 'asr': 1, 'ubfx': 1, 'sxtb': 1, 'uxtb': 1,
    'strb': 1, 'ldrb': 2, 'strh': 1, 'ldrh': 2,
    'subs': 1, 'adds': 1, 'movw': 1, 'movt': 1, 'it': 0,
    'strb.w': 1, 'ldrb.w': 2,
    'vmrs': 1, 'vmsr': 1, 'ble': 3, 'bmi': 3, 'bpl': 3,
    'bls': 3, 'bgt': 3, 'blo': 3, 'bhs': 3, 'bhi': 3, 'blt': 3,
    'bcc': 3, 'bcs': 3, 'd1': 3, 'dbne': 3, 'dbeq': 3,
    'dsb': 1, 'isb': 1,
}


def count_cycles_asm(asm_lines):
    """Static WCET: sum latencies. Default 2 cycles for unknown."""
    total = 0
    for mn in asm_lines:
        key = mn.split()[0].lower() if mn else ''
        # strip .w suffix and .f32/.f64 variant suffix
        key = key.replace('.w', '')
        key = key.split('.')[0]
        total += CM4_LATENCY.get(key, 2)
    return total


# ──────────────────────────────────────────────
#  Main — benchmark the found controllers
# ──────────────────────────────────────────────

if __name__ == "__main__":
    from racs2 import NonMinPhase, cfg
    from dso import ResourceContract
    import pickle
    verbose = len(sys.argv) > 1 and sys.argv[1] == '-v'

    # load NSGA-II results, test best controllers
    with open('/tmp/racs_nsga_results.pkl', 'rb') as f:
        all_rows = pickle.load(f)

    print("=" * 70)
    print("  RACS Codegen — Real Cortex-M4 Cycle Measurement (QEMU)")
    print("=" * 70)

    tests = []
    for plant_name, rows in all_rows.items():
        if rows:
            tests.append((plant_name, rows[0]))  # best by IAE

    print(f"\n  Testing {len(tests)} controllers (best-by-IAE per plant):\n")
    for plant_name, row in tests:
        tree = row['tree']
        print(f"  {plant_name[:30]:<32} model_cycles={row['cycles']:3d}")
        print(f"    formula: {row['formula']}")

        static_c, qemu_avg, info = measure_real_cycles(tree)
        if static_c is not None:
            print(f"    STATIC WCET (objdump+latency): {static_c:3d} cycles  "
                  f"(model={row['cycles']}, ratio={static_c/max(1,row['cycles']):.2f}x)")
            print(f"    asm instr: {info['asm_instr_count']}  |  qemu_avg: {info.get('qemu_avg')}")
            if verbose:
                print(f"    asm: {info['asm']}")
        else:
            print(f"    ERROR: {info.get('error', 'no cycles measured')}")

    # Also test a constant + simple expression for baseline
    print("\n  --- Reference: simple controllers ---")
    from racs2 import Node
    simple = [
        ("constant 1.0", Node('const', val=1.0)),
        ("e", Node('var', val='e')),
        ("e+r", Node('add', left=Node('var', val='e'), right=Node('var', val='r'))),
        ("e+ie+de+r+y", None),
    ]
    simple[3] = ("e+ie+de+r+y",
                 Node('add', left=Node('add', left=Node('add', left=Node('add',
                    left=Node('var', val='e'), right=Node('var', val='ie')),
                    right=Node('var', val='de')), right=Node('var', val='r')),
                    right=Node('var', val='y')))

    for name, tree in simple:
        static_c, qemu_avg, info = measure_real_cycles(tree)
        model = tree.cycles()
        if static_c is not None:
            print(f"  {name:<20} model={model:3d}  static={static_c:3d}  "
                  f"asm_instr={info['asm_instr_count']}")
        else:
            print(f"  {name:<20} ERROR: {info.get('error', '?')}")

    print("\nDone.")
